### PR TITLE
Fixed theme dependencies

### PR DESCRIPTION
**Pull request by JianLoong**
This PR is to handle #6 

I think I found your problem with it. Basically, what happened was, the project was using this [theme](https://github.com/dim0627/hugo_theme_robust) as a git submodule and because it was updated, it seem to have broken something. At first I thought it was because of the Hugo version as well.

What I have done is, instead of using it as submodule I included all the theme files needed to generate your blog in the themes directory. I am also using an older version of the theme (A version before they introduced SCSS dated **December 2019**). This way the site will not break so during any more updates of that theme as well.

It seems to be working on my local machine using Hugo v0.75.1.

Hopefully this helps you out.  :smiley:

### CODE REVIEW

**Comment by zo0o0ot** [comment]
I tried starting your branch in GitPod.  Good news: no more error!  Bad news: it still doesn't seem to show the images in the posts.

Version of Hugo in GitPod:
Hugo Static Site Generator v0.68.3/extended linux/amd64 BuildDate: 2020-03-25T06:15:45Z

Is the img shortcode broken?

**Comment by zo0o0ot** [comment]
An example of [an existing page](https://sermonarchives.github.io/sermons/a-fathers-heart-he-turned-to-me-1977/):
image

Hugo server running in GitPod:
image

Are you seeing the image when running locally?

**Comment by JianLoong** [comment]
I was just looking at GitPod, it seems the reason this happens because of the URL generated for preview purposes.

So if you actually did a 
```
hugo server or hugo server -D
```
to run it, it will not look nice because that is supposed to be for development. If you look at the generated files under public would be correct but the demo itself is not working on GitPod because it is mapped to localhost instead of the live url instead.

That being said, I tried to run the command below on GitPod instead

```
hugo server -b https://1313-c40017b2-ba54-4783-9c76-73b58c0603ba.ws-us02.gitpod.io -D --appendPort=false
```
and it seems to be working fine. **(You will need to put the correct url in the command for it to be working)**

What is happening here is that I specifically ask it generated with that base url without appending the port number.

Screenshot from 2020-10-08 17-39-33

Do tell me if this works. :relieved:

**Comment by zo0o0ot** [comment]
I'm going to merge this, because I can always revert the commit later.

**Comment by zo0o0ot** [comment]
To be clear, preview images seem to be working fine, it was the images that were in posts that were missing.

**Pull request merged**
